use QLBONGDA
--Phân quyền
GRANT SELECT ON vCau1 TO BDRead;
GRANT SELECT ON vCau2 TO BDRead;
GRANT SELECT ON vCau3 TO BDRead;
GRANT SELECT ON vCau4 TO BDRead;
GRANT SELECT ON vCau5 TO BDRead;
GRANT SELECT ON vCau6 TO BDRead;
GRANT SELECT ON vCau7 TO BDRead;
GRANT SELECT ON vCau8 TO BDRead;
GRANT SELECT ON vCau9 TO BDRead;
GRANT SELECT ON vCau10 TO BDRead;
--BDU01 
GRANT SELECT ON vCau5 TO BDU01 ;
GRANT SELECT ON vCau6 TO BDU01 ;
GRANT SELECT ON vCau7 TO BDU01 ;
GRANT SELECT ON vCau8 TO BDU01 ;
GRANT SELECT ON vCau9 TO BDU01 ;
GRANT SELECT ON vCau10 TO BDU01 ;
--BDU03 
GRANT SELECT ON vCau1 TO BDU03 ;
GRANT SELECT ON vCau2 TO BDU03 ;
GRANT SELECT ON vCau3 TO BDU03 ;
GRANT SELECT ON vCau4 TO BDU03 ;
--BDU04 
GRANT SELECT ON vCau1 TO BDU04 ;
GRANT SELECT ON vCau2 TO BDU04;
GRANT SELECT ON vCau3 TO BDU04 ;
GRANT SELECT ON vCau4 TO BDU04 ;