USE QLBONGDA
GO
CREATE VIEW [vCau1] AS 
SELECT MACT, HOTEN, NGAYSINH, DIACHI, VITRI
FROM CAUTHU
WHERE MACLB = (SELECT MACLB FROM CAULACBO
WHERE TENCLB = N'SHB Đà Nẵng' AND CAUTHU.MAQG =
(SELECT MAQG FROM QUOCGIA 
WHERE TENQG = N'Brazil'))
GO
SELECT * FROM [vCau1]
USE QLBONGDA
GO
CREATE VIEW [vCau2] AS
SELECT MATRAN, NGAYTD,CLB1.TENCLB
AS[CLB1], CLB2.TENCLB AS [CLB2], KETQUA
FROM TRANDAU, CAULACBO AS CLB1, CAULACBO AS CLB2, SANVD AS SANVD
WHERE TRANDAU.MASAN = SANVD.MASAN
AND TRANDAU.MACLB1 =  CLB1.MACLB
AND TRANDAU.MACLB2 = CLB2.MACLB
AND VONG = 3 
AND NAM = 2009
GO
SELECT * FROM [vCau2]
USE QLBONGDA
GO
CREATE VIEW [vCau3] AS
SELECT hlv.MAHLV, hlv.TENHLV, hlv.NGAYSINH, hlv.DIACHI, hc.VAITRO, clb.TENCLB
FROM HUANLUYENVIEN hlv, HLV_CLB hc, CAULACBO clb
WHERE hlv.MAHLV = hc.MAHLV 
AND hc.MACLB = clb.MACLB 
AND hlv.MAQG = (SELECT MAQG FROM QUOCGIA WHERE TENQG = N'Việt Nam')
GO
SELECT * FROM [vCau3]

USE QLBONGDA
GO
CREATE VIEW [vCau4] AS
SELECT CLB.MACLB, TENCLB, TENSAN, SVD.DIACHI, count(CT.MACT) AS SOCAUTHUNUOCNGOAI
FROM CAULACBO CLB, SANVD SVD, CAUTHU CT
WHERE CLB.MASAN = SVD.MASAN 
AND CLB.MACLB = CT.MACLB 
AND CT.MAQG NOT LIKE (SELECT MAQG FROM QUOCGIA WHERE TENQG = N'Việt Nam')
GROUP BY CLB.MACLB, TENCLB, TENSAN, SVD.DIACHI
HAVING COUNT(CT.MACLB) > 2
GO
SELECT * FROM [vCau4]
USE QLBONGDA
GO
CREATE VIEW [vCau5] AS
SELECT TENTINH, COUNT(MACT) AS SO_CT
FROM TINH AS TINH, CAULACBO AS CLB, CAUTHU 
WHERE TINH.MATINH = CLB.MATINH
AND CLB.MACLB = CAUTHU.MACLB
AND VITRI = N'tiền đạo'
GROUP BY TENTINH 
GO
SELECT * FROM [vCau5]
USE QLBONGDA
GO
CREATE VIEW [vCau6] AS
SELECT TENCLB, TENTINH
FROM CAULACBO AS CLB, TINH AS TINH 
WHERE CLB.MATINH = TINH.MATINH
AND CLB.MACLB = (SELECT MACLB FROM BANGXH
WHERE VONG = 3 AND NAM = 2009
AND HANG = 1)
GO
SELECT * FROM [vCau6]

USE QLBONGDA
GO
CREATE VIEW [vCau7] AS
SELECT TENHLV
FROM HUANLUYENVIEN hlv
INNER JOIN HLV_CLB hc ON hlv.MAHLV = hc.MAHLV
WHERE hlv.DIENTHOAI IS NULL;
GO
SELECT * FROM [vCau7]



USE QLBONGDA
GO
CREATE VIEW [vCau8] AS
SELECT TENHLV 
FROM HUANLUYENVIEN AS HLV, HLV_CLB, QUOCGIA AS QUOCGIA
WHERE HLV.MAHLV = HLV_CLB.MAHLV
AND MACLB IS NULL AND QUOCGIA.MAQG = HLV.MAQG 
AND TENQG = N'Việt Nam'
GO
SELECT * FROM [vCau8]
USE QLBONGDA
GO
CREATE VIEW [vCau9] AS
SELECT NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD, SANVD SVD, CAULACBO CLB1, CAULACBO CLB2
WHERE TD.MASAN = SVD.MASAN 
AND TD.MACLB1 = CLB1.MACLB 
AND CLB2.MACLB = TD.MACLB2 
AND TD.VONG <= 3 
AND TD.NAM = 2009
AND ((TD.MACLB1 = (SELECT MACLB FROM BANGXH WHERE VONG = 3 
AND NAM = 2009 AND HANG = 1)) OR 
(TD.MACLB2 = (SELECT MACLB 
FROM BANGXH WHERE VONG = 3 AND NAM = 2009 AND HANG = 1)))
GO
SELECT * FROM [vCau9]
USE QLBONGDA
GO
CREATE VIEW [vCau10] AS
SELECT NGAYTD, SVD.TENSAN, CLB1.TENCLB AS TENCLB1, CLB2.TENCLB AS TENCLB2, KETQUA
FROM TRANDAU TD, SANVD SVD, CAULACBO CLB1, CAULACBO CLB2
WHERE TD.MASAN = SVD.MASAN 
AND TD.MACLB1 = CLB1.MACLB 
AND CLB2.MACLB = TD.MACLB2 
AND TD.VONG <= 3 AND TD.NAM = 2009
AND ((TD.MACLB1 = (SELECT MACLB 
FROM BANGXH WHERE VONG = 3 AND NAM = 2009 
AND HANG >= ALL(SELECT HANG FROM BANGXH 
WHERE VONG = 3 AND NAM = 2009))) OR 
(TD.MACLB2 = (SELECT MACLB 
FROM BANGXH WHERE VONG = 3 AND 
NAM = 2009 AND HANG >= ALL(SELECT HANG FROM BANGXH 
WHERE VONG = 3 AND NAM = 2009))))
GO
SELECT * FROM [vCau10]





